hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?currentSchema=bolsa&socketTimeout=30&connectTimeout=10&tcpKeepAlive=true
hibernate.connection.username=postgres.jdsgehsflfwzlatcrjpj
hibernate.connection.password=YKDkuwPYMJFflBoi
hibernate.hbm2ddl.auto=update
hibernate.default_schema=mercadinho
hibernate.jdbc.lob.non_contextual_creation=true
